name: json_isolate
description: A helper class that will help you convert your json in the background using an isolate.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  isolate: ^2.0.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
